# Library path
snarkjsPath: "./node_modules/snarkjs/build/cli.cjs"
circomPath: "~/.cargo/bin/circom"
circomFlags: "--O0 --r1cs --wasm --json --verbose"


# Root path of the working directory of the `zkey-manager`
out: "./artifacts"


# Circom circuit config
circuits:
- template: "./circuits/merkleTree.circom"
  component: "Main"
  params: [25]
  pubInputs: ["root"]
  type: "test"
- template: "./circuits/mainCkt.circom"
  component: "Main"
  params: [4]
  pubInputs: ["metric", "average", "variance", "value", "value_SDM", "score"]
  type: "test"


# Powers of Tau ceremony file
ptauFiles:
  1:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_01.ptau"
      name: "powersOfTau28_hez_final_01.ptau"

  2:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_02.ptau"
      name: "powersOfTau28_hez_final_02.ptau"

  3:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_03.ptau"
      name: "powersOfTau28_hez_final_03.ptau"

  4:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_04.ptau"
      name: "powersOfTau28_hez_final_04.ptau"

  5:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_05.ptau"
      name: "powersOfTau28_hez_final_05.ptau"

  6:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_06.ptau"
      name: "powersOfTau28_hez_final_06.ptau"

  7:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_07.ptau"
      name: "powersOfTau28_hez_final_07.ptau"

  8:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_08.ptau"
      name: "powersOfTau28_hez_final_08.ptau"

  9:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_09.ptau"
      name: "powersOfTau28_hez_final_09.ptau"

  10:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_10.ptau"
      name: "powersOfTau28_hez_final_10.ptau"

  11:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_11.ptau"
      name: "powersOfTau28_hez_final_11.ptau"

  12:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_12.ptau"
      name: "powersOfTau28_hez_final_12.ptau"

  13:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_13.ptau"
      name: "powersOfTau28_hez_final_13.ptau"

  14:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_14.ptau"
      name: "powersOfTau28_hez_final_14.ptau"

  15:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_15.ptau"
      name: "powersOfTau28_hez_final_15.ptau"

  16:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_16.ptau"
      name: "powersOfTau28_hez_final_16.ptau"

  17:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_17.ptau"
      name: "powersOfTau28_hez_final_17.ptau"

  18:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_18.ptau"
      name: "powersOfTau28_hez_final_18.ptau"

  19:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_19.ptau"
      name: "powersOfTau28_hez_final_19.ptau"

  20:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_20.ptau"
      name: "powersOfTau28_hez_final_20.ptau"

  21:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_21.ptau"
      name: "powersOfTau28_hez_final_21.ptau"

  22:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_22.ptau"
      name: "powersOfTau28_hez_final_22.ptau"

  23:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_23.ptau"
      name: "powersOfTau28_hez_final_23.ptau"

  24:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_24.ptau"
      name: "powersOfTau28_hez_final_24.ptau"

  25:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_25.ptau"
      name: "powersOfTau28_hez_final_25.ptau"

  26:
      url: "https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_26.ptau"
      name: "powersOfTau28_hez_final_26.ptau"
